version: "3"
services:
  datax_web_mysql:
    image: mysql:5.7
    restart: always
    tty: true
    volumes:
      - ./db/init.sql:/tmp/init.sql
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: dataxweb
      TZ: Asia/Shanghai
      character-set-server:  utf8mb4
      collation-server: utf8mb4_unicode_ci
    ports:
      - 3307:3306
    container_name: datax_web_mysql_c
  datax_web:
    build:
      context: ./datax-web
    container_name: datax_web_c
    ports:
      - 9527:9527
    volumes:
      - ./job:/data
    tty: true
    restart: always
    networks:
      - default
