version: "3.8"
services:
  mongodb:
    image: mongo:3.4.24
    container_name: mongodb_c
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
